### ISSUE TITLE
Publication date placed in the wrong place

### ISSUE THREAD

**Issue by dsiev** [michal-h21/biblatex-iso690#126]
I am using the german version of your package.
The publication date should be placed after the author but for some reason it gets placed after even the publisher and the title (see the following image).
![image](https://github.com/michal-h21/biblatex-iso690/assets/133495111/6c13f37d-1844-4c12-a063-92f522b8ccf1)
I have used following entries in the .bib file:
![image](https://github.com/michal-h21/biblatex-iso690/assets/133495111/c246addf-47af-4b22-82d2-1d7298995d2d)
and the following packages:
![image](https://github.com/michal-h21/biblatex-iso690/assets/133495111/676d78d2-9f70-435e-a20e-8b6f9003362f)

**Comment by dsiev** [comment]
It should look something like this according to your documentation.
![image](https://github.com/michal-h21/biblatex-iso690/assets/133495111/4ed8635c-cf75-44d2-a0f8-4269c012c104)

**Comment by dsiev** [comment]
Here's a minimal working example
https://de.overleaf.com/read/cdbqpmszndwn

**Comment by dsiev** [comment]
Here's a minimal working example
https://de.overleaf.com/read/cdbqpmszndwn

**Comment by michal-h21** [comment]
@dsiev the date right after the author is used only in the `iso-authoryear` style. You use `iso-numeric`. With this style, the date should be placed after the publisher. This is the standard placement of this field, in author-year it is different only because the author and date are primary identifiers, so they need to be placed at the beginning of the reference entry.
