### ISSUE TITLE
iso-numeric has "1" instead of "[1]" before bibliography entries

### ISSUE THREAD

**Issue by henczati** [michal-h21/biblatex-iso690#17]
Is this intentional or a bug?

**Comment by moewew** [comment]
Regardless of this is intentional or a deviation from ISO, you can have brackets using

```
\DeclareFieldFormat{labelnumberwidth}{\mkbibbrackets{#1}}
``` 

As far as I can see the usage of `labelnumberwidth` in `iso-numeric.bbx` is at least slightly problematic, because `labelnumberwidth` is not defined in any of the bundled styles (it is defined in `numeric.bbx`, but that is not loaded by any of the `iso*` styles).

So this definition should probably feature in `numeric-iso.bbx` or somewhere.

**Comment by michal-h21** [comment]
It should be `1.` according the norm. I've added definition for
`labelnumberwidth` to print number with dot.

**Comment by henczati** [comment]
Thanks for the fix.

**Comment by DavidLuptak** [comment]
Explained and solution proposed, incorporated in the [Style Guide](https://github.com/michal-h21/biblatex-iso690/wiki/Style-Guide) wiki page, closing.
