### ISSUE TITLE
Changes to name handling in biblatex >= 3.3

### ISSUE THREAD

**Issue by moewew** [michal-h21/biblatex-iso690#24]
The handling of names has drastically changed in biblatex >= 3.3. `\DeclareNameFormat` has a new syntax now, the name formats are renamed from `last-first` to `family-given` etc. and `\mkbibnamelast` is now `\mkbibnamefamily`.

I will look into changing the code so that it works with biblatex >= 3.3 as expected and doesn't lose backwards compatibility.

**Comment by michal-h21** [comment]
It seems that the new biblatex version has lots of changes, I am currently
struggling with tex4ht config file, it doesn't output any references at the
moment.

**Comment by johannesbottcher** [comment]
Sorry, i couldn't resist. Since when can i *add my reaction*?

@moewew `biblatex-iest` has updated as well. i think a backwards compatible thing is needed there as well.

**Comment by moewew** [comment]
Oh, yes that is another problem. I think I have the name format changes under control for this style here. But that is only down to fortunate circumstances.
Does anyone have an older version of `biblatex` to test against pull request #25?

**Comment by johannesbottcher** [comment]
Not at hand, but see http://texwelt.de/wissen/fragen/16635/downgrade-biber

**Comment by moewew** [comment]
@johannesbottcher  Thanks, I'm still running MikTeX, though. 

----

Just checked the changes against biblatex 2.9a/Biber 1.9 and everything seemed fine. So we are hopefully good here.

**Comment by moewew** [comment]
## TODO

The `labelname` format in https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authortitle.cbx needs looking at. (Should be incompatible with v. 3.3)

What about the cite macro in https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authoryear.cbx couldn't we just take the standard definition?

Can we get rid of \MethodFormat in the `.bbx` files?

Do we need `year-label` in https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authoryear.bbx?

Make the backwards compatibility code for `\mkbibname...` not throw warnings with newer versions. (Branch on `biblatex` version?)

Get rid of unused code in `iso.bbx` and general code clean-up.

**Comment by DavidLuptak** [comment]
> The labelname format in https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authortitle.cbx needs looking at. (Should be incompatible with v. 3.3)

I have looked at it and the change could be find in the new branch `biblatex>=3.4`. In `iso.bbx` we use `\DeclareNameAlias{default}{last-first}`, new biblatex version uses `\DeclareNameAlias{default}{family-given}`, but the former is still provided as an alias for the latter. Maybe after some time we could incorporate this also into master branch.

> What about the cite macro in https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authoryear.cbx couldn't we just take the standard definition?

Resolved, see 1ca693a4d38aac9a6480575bd0a3408a5b1f4be4.

> Can we get rid of \MethodFormat in the .bbx files?

We need it for numeric style, but we can redefine a whole `\defbibenvironment{bibliography}` including this `\MethodFormat` in `iso-numeric.bbx` and remove an appearance of `\MethodFormat{}` from others `*.bbx` files. Or is there some more elegant solution for this?

> Do we need year-label in https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authoryear.bbx?

I think, yes, we need, because of printing year right after creators' names when citing by harvard style. Again, is there some more elegant solution for this?

> Make the backwards compatibility code for \mkbibname... not throw warnings with newer versions. 

I cannot reproduce such warnings with biblatex 3.4 and biber 2.5.

> Get rid of unused code in iso.bbx and general code clean-up.

Keep working on it.

**Comment by moewew** [comment]
The `labelname` format I alluded to is the special one in `iso-authortitle.cbx` (https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authortitle.cbx#L8). I don't know exactly why it's there, but I'm very confident that whatever it ought to do can be done in a less intrusive manner.

The question of whether to use `last-first` or `family-given` is also interesting. `last-first` will provide backwards compatibility for older versions, on the other hand it is nice to use the proper (non-deprecated) formats. Either we do some internal version checking, or we drop support for older `biblatex` versions after some time ...

> We need it for numeric style, but we can redefine a whole `\defbibenvironment{bibliography}` including this `\MethodFormat` in `iso-numeric.bbx` and remove an appearance of `\MethodFormat{}` from others `*.bbx` files. Or is there some more elegant solution for this?

What you describe is how the standard `biblatex` styles do it, I'm therefore prone to advocate that approach. I can't think of a more elegant approach, but clearly that doesn't mean that there isn't one.

> > Do we need `year-label` [...]?
> I think, yes [...].

The standard styles solve that slightly differently by embedding the year printing into the name macros, but I will be the first to admit that that takes quite some code. In our case, however, that would probably only mean to redefine `names:primary`. The difference is not big, but I prefer to have all macros used in `iso.bbx` to be at least defined in a skeleton version there - `year-label` is only defined in the additional `.bbx` files.

> > Make the backwards compatibility code for \mkbibname... not throw warnings with newer versions. 
> I cannot reproduce such warnings with biblatex 3.4 and biber 2.5.

Ahhh, yes, I see now that because we delay the assignment to `\AtBeginBibliography` we don't get to see the warning. Never mind then.

**Comment by DavidLuptak** [comment]
Since `author-title` style is not introduced as a method of citation in ISO 690 and also @michal-h21  [have added it just for completness](https://github.com/michal-h21/biblatex-iso690/issues/19#issuecomment-162304791), I would suggest to get rid of it. Still one (running notes) of three (author-year, numeric, running notes) methods of citation is not supported here. Need to wait for @michal-h21 input.

I would suggest to provide backwards compatibility for this moment, and later on just drop it.

> What you describe is how the standard biblatex styles do it, I'm therefore prone to advocate that approach. I can't think of a more elegant approach, but clearly that doesn't mean that there isn't one.

The elegant solution which has appeared is move `\MethodFormat` into `iso.bbx` since `labelnumber` needs to be requested by package option and this is requested just in the `iso-numeric.bbx` file. However, printing the dot by `labelnumberwidth` format needs to be retained in `iso-numeric.bbx`. I hope it's still working as desired.

>>> Do we need year-label [...]?

>> I think, yes [...].

> The standard styles solve that slightly differently [...].

I understand the idea but somehow don't know how to incorporate it there.

> [...]. Never mind then.

However, we can see deprecation warning caused by `labelprefix`. But that will be there until we drop the backwards compatibility support for this, won't it?

**Comment by moewew** [comment]
> The elegant solution which has appeared is move \MethodFormat into iso.bbx since labelnumber needs to be requested by package option and this is requested just in the iso-numeric.bbx file. However, printing the dot by labelnumberwidth format needs to be retained in iso-numeric.bbx. I hope it's still working as desired.

OK, I would have found it safer to go with the standard approach, but if you feel that this is en elegant solution, that is fine as well.

> I understand the idea but somehow don't know how to incorporate it there.

I would just go with
```
\newbibmacro*{names:primary}{%
  \ifboolexpr{
    test \ifuseauthor
    and
    not test {\ifnameundef{author}}
  }
    {\usebibmacro{author}}
    {\usebibmacro{editor}}%
  \setunit{\addspace}\printfield{nameaddon}%
  \setunit{\addcomma\space}%
}
```
in `iso.bbx`.

And then in `iso-authoryear.bbx` add the redefinition
```
\renewbibmacro*{names:primary}{%
  \ifboolexpr{
    test \ifuseauthor
    and
    not test {\ifnameundef{author}}
  }
    {\usebibmacro{author}}
    {\usebibmacro{editor}}%
  \setunit{\addspace}\printfield{nameaddon}%
  \setunit{\addcomma\space}%
  \ifboolexpr{not test {\ifnameundef{author}} or not test {\ifnameundef{editor}}}
    {\printextrayear}
    {}}
```

This will do away with the slightly confusing `year-label` macro that does nothing most of the time at the cost of a bit more code in `iso-authoryear.bbx`.

> However, we can see deprecation warning caused by `labelprefix`.

Oh, yes, instead of testing against `\iffieldundef{labelprefix}` we should probably test against `\@ifpackagelater{biblatex}{<release date of v. biblatex 3.4>}`

**Comment by DavidLuptak** [comment]
> OK, I would have found it safer to go with the standard approach, but if you feel that this is en elegant solution, that is fine as well.

Yes, of course, it might be really not safe and clear. I meant "elegant" in a way of having less code there.. After all, let's use the standard approach.

> year-label

Now I see. But we have a problem. Since incorporating macro `editor`with it's last line `\clearname{editor}` to avoid printing such editor second time in section of subsidiary editors, this fails the test for `\printextrayear` in `iso-authoryear` style. Even more, we can not deal such situation when title is used instead of creator name (encyclopedia etc., section 5.4.3 of the norm) and printing the year after title when citing by `iso-authoryear` style.

> \@ifpackagelater{biblatex}{<release date of v. biblatex 3.4>}

I replace the appropriate code in this way, but it ended up with compilation error.
```tex
\@ifpackagelater{biblatex}{2016/03/27}
      {\printfield{labelprefix}}
      {\printfield{prefixnumber}}%
```

**Comment by moewew** [comment]
> Now I see. But we have a problem. ...

But that problem should also occur with the code currently used, right? Maybe you should investigate what the standard styles (`authoryear`) do here. I think they come very close to what you need.

> `\@ifpackagelater{biblatex}{}`

Ah yes, you can't use `\@ifpackagelater` from within a macro, you will have to branch on the definitions like

```
\@ifpackagelater{biblatex}{2016/03/27}
  {\newcommand\MethodFormat{%
     \printtext[labelnumberwidth]{%
        \printfield{labelprefix}%
        \printfield{labelnumber}}}}%
  {\newcommand\MethodFormat{%
     \printtext[labelnumberwidth]{%
        \printfield{prefixnumber}%
        \printfield{labelnumber}}}}%
```

But the worst that happens if we use
```
\newcommand\MethodFormat{%
  \printtext[labelnumberwidth]{%
    \printfield{prefixnumber}%
    \printfield{labelprefix}%
    \printfield{labelnumber}}%
}%
```
is the warning. Maybe we can drop `prefixnumber` after some grace period.

**Comment by DavidLuptak** [comment]
> But that problem should also occur with the code currently used, right?

Yes, right. See 6006cc1117585cc07de25aaef5e2c89ab5030ed2

> prefixnumber

Incorporated, see e3d920cd5969ffffad5c7fe2d2783f73e8678bb6

**Comment by moewew** [comment]
The issue of the `labelname` in `authortitle.cbx` still needs looking at. I don't know what the expected output is, but the code there cannot be used to obtain any useful output with `bibilatex` >= 3.3.

See https://github.com/michal-h21/biblatex-iso690/blob/master/iso-authortitle.cbx#L8

**Comment by DavidLuptak** [comment]
Do we need to keep `authortitle.cbx` at all? Because I don't know the expected output as well. I have previously proposed [my intention](https://github.com/michal-h21/biblatex-iso690/issues/24#issuecomment-216350831). Though it's getting around, not overcoming the obstacle.

**Comment by moewew** [comment]
Of course that is the easy get-away plan. But it would be equally easy to keep the file around and just delete the offending redefinition of `labelname`. The rest should work (once all the `authoryear`s in that file are replaced with `authortitle`) out of the box.
