### ISSUE TITLE
Publish on CTAN

### ISSUE THREAD

**Issue by Crissov** [michal-h21/biblatex-iso690#29]
This package really should be available through [CTAN](http://www.ctan.org/upload) so it could be better found by users and easier installed with package managers.

**Comment by michal-h21** [comment]
It is definitely a plan we have, but I think we should fix incompatibilities with Biblatex core first

**Comment by Witiko** [comment]
Are you planning to get the package into TL16? Note that the code freeze [is scheduled](https://www.tug.org/texlive/) on May the 4th.

**Comment by DavidLuptak** [comment]
@michal-h21 @moewew @johannesbottcher Are we ready to publish yet?

**Comment by DavidLuptak** [comment]
I am going to publish `biblatex-iso690` on CTAN to meet the deadline for TeX Live 2016. I have prepared a [zip to upload](https://www.dropbox.com/s/4hlli7pdru4lxx0/biblatex-iso690.zip?dl=0). This archive is lacking the following files:
* [bibpok.tex](https://github.com/michal-h21/biblatex-iso690/blob/master/bibpok.tex) since a reference bibliography is already in [biblatex-iso690.tex](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690.tex)
* [iso.txt](https://github.com/michal-h21/biblatex-iso690/blob/master/iso.txt) since it might not be relevant
* [iso-example.tex](https://github.com/michal-h21/biblatex-iso690/blob/master/iso-example.tex) and [iso-example.tex](https://github.com/michal-h21/biblatex-iso690/blob/master/iso-example.tex) since they are outdated and only in Czech ([biblatex-iso690.tex](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690.tex) and  [biblatex-iso690.pdf](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690.pdf) serve as a replacement)

I would be very glad for any suggestions, especially what to fill in the field "Suggested CTAN directory" on the [upload page](http://www.ctan.org/upload) -- is `tex-archive/bibliography` correct one? And how can one specify a topic (at least `https://www.ctan.org/topic/biblatex`) there? Thanks.

**Comment by moewew** [comment]
Did you get any input on the license issue from @michal-h21?

**Comment by DavidLuptak** [comment]
No, I have the latest reply from @michal-h21 ten days old. Well, I would keep the GNU GPL 3 for now.

**Comment by Witiko** [comment]
I would suggest the CTAN directory of `/macros/latex/contrib/biblatex-contrib/biblatex-iso690`, since that seems to be the general scheme for biblatex contributions. You can use the Administrative notes field to ask the CTAN maintainer to set a topic to your package.

**Comment by DavidLuptak** [comment]
Well, here it is [https://www.ctan.org/pkg/biblatex-iso690](https://www.ctan.org/pkg/biblatex-iso690). See also the [release](https://github.com/michal-h21/biblatex-iso690/releases/tag/v0.3.1) in the respective section of this GitHub repository. Thanks!
