### ISSUE TITLE
phdthesis displays no school

### ISSUE THREAD

**Issue by hroncok** [michal-h21/biblatex-iso690#34]
Consider the following record:

```
@phdthesis{rest,
	author = {Roy Thomas Fielding},
	title = {{Architectural Styles and the Design of Network-based Software Architectures}},
	url = {http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm},
	year = {2000},
	school = {{University of California, Irvine}},
}
```

And this is what I see:

![phdthesis](https://cloud.githubusercontent.com/assets/2401856/14233533/d58c0474-f9cb-11e5-9bdf-a37ce4de9d7c.png)

I was expecting to see something like:

    PhD thesis, University of California, Irvine, 2000.

I'm using `iso-numeric`. With `alphabetic`, thsi is what I see:

![phdthesis2](https://cloud.githubusercontent.com/assets/2401856/14233548/72f35866-f9cc-11e5-8de1-e218fa576427.png)

So I guess the problem is somewhere in `iso-numeric` style. Can you please help me with that?

**Comment by johannesbottcher** [comment]
Have you tried `institution` instead of school?

**Comment by hroncok** [comment]
Right now, didn't help.

**Comment by johannesbottcher** [comment]
`biblatex`  maps school to institution, unfortunately `biblatex-iso` doesn't use `institution` in any case. 

@moewew How much time do you think would a rewrite take?

**Comment by moewew** [comment]
Unfortunately, currently the style really only has drivers for `@book`, `@article`, `@inbook`, `@incollection` and `@online`.

The `@thesis` type for example is mapped to `@book` and so it doesn't support `institution` or even `type`. A work-around is to use the `note` field, sorry. (Not entirely sure if you can give the institution as `publisher` and get away with that.)


@johannesbottcher  It probably wouldn't be to hard to cobble together a `@thesis` driver, but I don't know the rules and am a bit snowed under at the moment. There are some ad-hoc solutions in the code that I'm not sure if they can be re-used or not.

A complete re-write of the entire style to bring it in line with current `biblatex` styles while keeping the additional modification to a minimum is more promising. But then we have discussed this whole ISO/DIN/standard thing so many times, I'm not even sure what a style with this name should do.

**Comment by hroncok** [comment]
> (Not entirely sure if you can give the institution as publisher and get away with that.)
I was thinking about that.

BTW [ISO 690 for thesis](https://sites.google.com/site/novaiso690/schema-a-priklady/diplomov-prce-p) is:

Author. *Title.* (Other titles.) Address, year. (Size.) Thesis type. School name. (Supervisor.)

Things in parenthesis are optional.

In this case:

> FIELDING, Roy Thomas. *Architectural Styles and the Design of Network-based
Software Architectures.* Irvine, 2000. Dissertation. University of California, Irvine.

I was able to have this:

@phdthesis{rest,
	author = {Roy Thomas Fielding},
	title = {{Architectural Styles and the Design of Network-based Software Architectures}},
	url = {http://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm},
	year = {2000},
	note = {{Irvine, 2000. Disertační práce. University of California, Irvine.}},
}

![phd4](https://cloud.githubusercontent.com/assets/2401856/14239620/dbcdb892-fa3d-11e5-82c7-a219b9bd2b1a.png)

And if I omit the URL:

![phd3](https://cloud.githubusercontent.com/assets/2401856/14239627/e7cd2ee8-fa3d-11e5-9e0e-aaa7476631eb.png)

Is there a way to hack the note to appear before the URL?

**Comment by johannesbottcher** [comment]
@moewew personally, i think i would rename the style because it is the more specific czech implementation of the international standard. That should only be a small amount added on top of biblatex.

**Comment by moewew** [comment]
@hroncok  Apparently, with this style the `note` always appears after the URL and other availability stuff taking the role of what `addendum` does in the standard `biblatex` styles. You can try using the `titleaddon` field for the thesis type. But it seems to me you need to write a proper driver, the abuse of fields can only get you so far.

@johannesbottcher Unfortunately that thing layer gets easily bloated as soon as you have to change the order of fields directly in the drivers (you could do that with `xpatch`, but if I were to write a style I would probably not use patching, but write the drivers properly: a common wish is to move the author/editor of the `booktitle` before the actual `booktitle`).

**Comment by johannesbottcher** [comment]
@moewew The drivers, you are right, didn't think about them. Much of the current code is from the beginnings of biblatex, which was extended quite a bit. You know this better than i do. 

I am a bit scared that people are attracted to the style because of its name, whereas it is a specialised subset of the generic iso 690.

**Comment by moewew** [comment]
> The drivers, you are right, didn't think about them. Much of the current code is from the beginnings of biblatex, which was extended quite a bit.

The drivers don't necessarily mean more work, but the feel of the code becomes another, the style is no longer a lightweight add-on, it becomes a bit harder to navigate. And there is more to do to keep up with `biblatex`'s changes (they rarely affect the drivers, but sometimes cool new features are added that would be nice to have).

> I am a bit scared that people are attracted to the style because of its name, whereas it is a specialised subset of the generic iso 690.

That is a real risk, yes. We have discussed this before (https://github.com/domhardt/BibLaTeX-DIN1505/issues/1).  And I'd be interested interested in how generic the established `.bst` "din" styles actually are. Maybe it would make sense to port those to `biblatex` if they are still widely used, well-liked, ISO/DIN compliant and generic enough.

**Comment by johannesbottcher** [comment]
> And I'd be interested interested in how generic the established .bst "din" styles actually are. Maybe it would make sense to port those to biblatex if they are still widely used, well-liked, ISO/DIN compliant and generic enough.

I don't have the old DIN at hand and you probably already know https://de.wikipedia.org/wiki/DIN_1505-2, following the link to the pdf at the very bottom gives some examples. It seems the DIN is less generic than the ISO, which is good, because `bst` files aren't that flexible. Have a look at the funny punctuation, where a colon can be written with space before/after/or both depending on the case. Madness.

**Comment by Lenchik** [comment]
Maybe [biblatex-gost](https://github.com/odomanov/biblatex-gost) can give you some ideas on modifications. It has some "biblatex magic" on implementing insertion on dissertation type and science field.

**Comment by DavidLuptak** [comment]
I am trying to add an entry field `supervisor` following also [this guide](http://tex.stackexchange.com/questions/184848/how-to-add-the-name-of-the-supervisor-in-a-thesis-field), everything works well until I want it not to load by biblatex package option `datamodel=<..>` but by the iso style itself by default. I have tried `\blx@inputonce` as well as `\input` put in the `iso.bbx`, but it just ends up with compilation error. Please, what am I doing wrong? How can be this achieved?

**Comment by moewew** [comment]
Have a look at §4.5.3 *Data Model Specification* of the `biblatex` docs. You can save the `.dbx` file as `<stylename>.dbx` and it will be loaded automatically. Otherwise you will have to use the `datamodel` option or resort to hacks or the https://www.ctan.org/pkg/biblatex-multiple-dm package.

**Comment by DavidLuptak** [comment]
Finally, I have used the first option and added new files `iso-numeric.dbx`, `iso-authoryear.dbx` and ` 	iso-authortitle.dbx`, and created new driver for `thesis` entry type accompanying by new option to print a url as one of the last elements in a reference. Personally, I am not sure whether this order meets the requirements of the norm or not, but here was a demand for this (and other reference managers are not uniform about this as well). Hence also new separate driver for `thesis`, not extension of existing `book` entry type as proposed in [thesis](https://github.com/michal-h21/biblatex-iso690/commits/thesis) branch.

**Comment by DavidLuptak** [comment]
Well, to the discussion about considering this package to be a specific subset of the generic ISO 690 standard -- you are right, the package is based on the international standard **as well as** some Czech interpretations. And that's because of, I would say, the ISO 690 itself, since it does not prescribe any particular style for the punctuation etc. and this package is based on many examples provided there which are just informative (**but** conforming the standard) and hence this package may be considered as a specific one. I am in to make this package as general as possible, and that's the work which is already done by the refactoring of the package, I hope. However, it should be also keep in mind to have the package usable which is in contrast with the generality..

To the issue -- it's already implemented as mentioned in the previous comment, now it should be working just fine. The package option for controlling the position of the thesis information changed from `thesisinfolast` to `thesisinfoinnotes` in 858ff17a8d58765bab7366b60091ab4e499e8d9c to better describe the purpose of this option.

Hence I would consider this ticket as resolved one and closing it for now.
