### ISSUE TITLE
Dates refactoring

### ISSUE THREAD

**Issue by DavidLuptak** [michal-h21/biblatex-iso690#75]
1. In numeric style, the style is missing the hierarchy of dates preference like it is accompanied with authoryear style:
```latex
\DeclareLabeldate{%
  \field{date}
  \field{year}
  \field{eventdate}
  \field{origdate}
  \literal{nodate}
}
```

2. The `@online` type is missing fuller dates in place of publication info (macro `location+publisher+date`) for authoryear style..

Follows #72

**Comment by moewew** [comment]
The `\DeclareLabeldate` hierarchy is only needed if the style uses `labeldate` with `\printlabeldate`. Usually `numeric`-like styles don't have any calls to `labeldate` printing macros.

**Comment by moewew** [comment]
For the `@online` date we can use the same trick as for `@patent`s until someone (\*cough\*) finally tackles https://github.com/plk/biblatex/issues/863

https://github.com/michal-h21/biblatex-iso690/blob/abf0c54c035ae325ee02ea8a5eaaa297aa34e806/iso.bbx#L473-L475

https://github.com/michal-h21/biblatex-iso690/blob/abf0c54c035ae325ee02ea8a5eaaa297aa34e806/iso.bbx#L1261-L1288

**Comment by DavidLuptak** [comment]
1. I meant the hierarchy in terms of printing `eventdate` or `origdate` if no `date` or `year` is given, and literal string `nodate` only as the last resort.

**Comment by moewew** [comment]
Thing is whether we need the hierarchy here.

In the standard styles each date has its position: `date` close to location and publisher, `eventdate` together with `venue` in parentheses after the `booktitle`, `urldate` near the URL, `origdate` is usually not printed. In that setting it makes little sense to substitute date type X for a missing date type Y, since type X is going to be printed in another position anyway (ignore `origdate` for now). The labeldate hierarchy only comes into play when it becomes more important for a work to have a year, namely when works are cited with author name and year. `biblatex` tries to avoid not printing a year (or adding `nodate`) as long as it can (indeed the `nodate` thing was only added to the labeldate hierarchy later, so before that the work would not have had a full citation label), so there it is useful to be able to fall back to other date types.

The issue with using the normal fallback for the `date` bibmacro is that one can't tell a work with only
```
origdate = {1999},
```
from a work with only
```
date = {1999},
```
in the output. Whether that is problematic according to the standard I don't know.

**Comment by DavidLuptak** [comment]
Well, you are right, this solution is probably not correct. We don't use `origdate` and `eventdate` fields at all except the respective bibmacro. There is also another things in the standard:
* for example, if the year is incorrect, it should be corrected in brackets after that. This was left to the creators of bib files that they provide only correct dates (no needs for corrections in the printed bibliography). Maybe we should think about some literal field `dateaddon` for this. Then it could be used also in place of `origdate` more universally:
> 1959 [i.e. 1995]

> 1796 copied 1810

> 2009, reprint 2011

* if there is a year with copyright, the symbol :copyright: or abbreviation `cop.` or term `copyright` should be also printed
  * I don't know if it would be possible something like `date = {c2020}` in a bib file to parse and print as `:copyright: 2020` in the bibliography
  * maybe a new field `copyrightdate` would be also possible, because sometimes publication date and copyright date may differ

There are also things with different calendar systems
> Jewish calendar 5685 [1925]

and centuries
> [16th century]

but they may be handled with `biblatex` facilities, I haven't looked at it yet.

I didn't deep into some of these thing before, because ISO 690 contains statements like this:
> If the date on the preferred source, e.g. a copyright date, is different from that of the publication date, both may be given.

**Comment by DavidLuptak** [comment]
Finally, I have added _only_ a new `dateaddon` literal field that could serve almost every use case I could come up with at the moment. I tried to document it with a lot of examples (in the documentation and/or bib file) thoroughly.

I will keep some notes here:
* `origdate` is not used, similar to the standard styles (except `labeldate`)
* `eventdate` is not used, ISO 690 does not contain particular part about this as I am aware of, so this information is optional (except `labeldate`)
* none of the other styles (a quick look at <https://ctan.org/topic/biblatex>) deal with a copyright date, so only `dateaddon` seems to me to be more universal to use than have one more `copyrightdate` field (compatibility issues of bib files between different styles)
