### ISSUE TITLE
urlalso is not translated in bulgarian

### ISSUE THREAD

**Issue by vgvassilev** [michal-h21/biblatex-iso690#76]
Hello,

  Here is a minimal working example and an pdf output file.

```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[english, bulgarian]{babel}

\usepackage[
    backend=biber
   ,style=iso-numeric
   ,sorting=none % order by occurence
   ,giveninits=true
   ,babel=other
   ,sortlocale=bg_BG
   ,bibencoding=UTF8
   ,labelnumber=true
]{biblatex}

% Print author names as small caps
%\let\lastnameformat=

\addbibresource{\jobname.bib}
\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
  @Patent{Edwards2003,
    author = {Edwards, Jermaine Charles},
    title  = {Method, system, and program for logging statements to monitor execution of a program},
    year   = {2003},
    date   = {2003-03-25},
    number = {6539501},
    holder = {Edwards},
    type   = {patentus},
    url    = {https://patents.google.com/patent/US6539501B1/en},
    langid = {en}
  }

  @Online{Clover,
    title = {OpenClover},
    url   = {http://openclover.org/},
    langid    = {en},
  }

}
\end{filecontents}

\begin{document}

\cite{Edwards2003},\cite{Clover};

\printbibliography

\end{document}

```

  I'd be happy if you give me some hints how to debug this.

Best, Vassil
[urlalso.pdf](https://github.com/michal-h21/biblatex-iso690/files/4138447/urlalso.pdf)

**Comment by DavidLuptak** [comment]
Hello, I cannot reproduce the issue with the latest developer version of the package (master branch on GitHub):

![Screenshot_2020-01-31 mwe pdf](https://user-images.githubusercontent.com/11637888/73532460-03665580-441d-11ea-90b7-dce2f098d9b4.png)

-----
So I suggest to have a look at the `biblatex-iso690` version you are using, however it is not so easy to catch it in the log files or so, because file headers were not updated with the latest release on CTAN.

The current CTAN release does not contain the Bulgarian localization yet, but we are preparing to upload the developer version soon. For now, only this GitHub version can solve your problem.

If you are satisfied with the answer, please close this issue, thanks :)

**Comment by vgvassilev** [comment]
I can confirm that this works in the master. Thanks!
