### ISSUE TITLE
Online medium type for theses / dissertations [reported issue]

### ISSUE THREAD

**Issue by DavidLuptak** [michal-h21/biblatex-iso690#80]
> A thesis or dissertation is almost always printed, so it is not an online resource (medium designation `[online]`, even though it is usually available in an archive in the electronic form.

Fair enough; usually the printed version is in the limited number of copies (let's say 2), so from the reader's point of view, it is more an online resource than a printed one. By quick survey among (not all!) citation generators / managers, I found that only Masaryk University thesis archive produces something similar to the `urldate` and `howpublished = {[online]}` fields, e.g. <https://is.muni.cz/th/422640/fi_b/?lang=en#panelbibtex>. So it is reasonable to skip the `urldate` and `howpublished = {online}` for `@thesis` entry types in the example [mybib.bib](https://github.com/michal-h21/biblatex-iso690/blob/master/mybib.bib#L209) file.

**Comment by moewew** [comment]
I don't know a lot about the exact wording and intent of ISO 690 and about the idea behind the online medium type (which I always found a bit weird anyway: surely people can tell online references from the fact that there is a URL?), but I don't think that a decision here should be heavily based on the result of `.bib` export tools from websites. In general those are not known to provide the most accurate data, see for example https://tex.stackexchange.com/q/386053/35864. And I definitely would not trust them with details related to ISO 690 hermeneutics.

I guess it all depends on what the idea behind medium designator is and how you treat sources that were published in multiple formats.

Is the medium designator based on the version of the work you actually consulted (probably the online version) or based on a version of the work that (probably) exists and that you could in theory get hold of? Does "online" mean *available (only) online* or does it mean *I accessed it online*? How similar would a physical work and its online version have to be to qualify as "the same" so that you can drop the "online" designator even though you only read the online version?

**Comment by DavidLuptak** [comment]
Thank you for the reply!

> [..] but I don't think that a decision here should be heavily based on the result of `.bib` export tools from websites. In general those are not known to provide the most accurate data, see for example https://tex.stackexchange.com/q/386053/35864. And I definitely would not trust them with details related to ISO 690 hermeneutics.

This package does not depend on the other tools by the reasons you mentioned and referenced. I have to admit I overlooked one more or less trustworthy source citace.com (they worked on the Czech interpretation of the ISO 690 standard), that differentiate between [printed](https://www.citacepro.com/vytvorit-prazdny-dokument?druh=5&bezPrihlaseni=1) and [electronic dissertations](https://www.citacepro.com/vytvorit-prazdny-dokument?druh=10&bezPrihlaseni=1) in their generator (sorry, it is only in Czech), where you can easily spot the difference in `[online]` and `urldate`. And they state that the *electronic dissertation* is for the works that are available in the electronic form online or in the digital archive (e.g. [theses.cz](https://theses.cz/?lang=en)).

The decision was based on the reporter's learning point of view, that students have problem to distinguish what to cite:

```
BAY, Herbert; ESS, Andreas; TUYTELAARS, Tinne; GOOL, Luc Van: Speeded-Up Robust Features (SURF) [online]. 2006, updated 2008 [cit. 2010-07-13].
Accessible from WWW: ftp://ftp.vision.ee.ethz.ch/publications/articles/eth_biwi_00517.pdf
```

versus

```
Herbert Bay, Andreas Ess, Tinne Tuytelaars, Luc Van Gool, „SURF: Speeded Up Robust Features“, Computer Vision and Image Understanding (CVIU), Vol. 110, No. 3, pp. 346–359, 2008
```

Examples gratefully obtained from <https://www.herout.net/blog/2010/08/evergreen-citovani-webu-vs-papiru/>.

> I guess it all depends on what the idea behind medium designator is and how you treat sources that were published in multiple formats.

I can cite the most relevant part of the standard for this:

> The creator of the reference should determine the appropriate level of specificity at which the reference is made (e.g. to an entire document or to a specific part of a document) based on the purposes of the citation and the use that was made of the material being cited.

[1, sec 3.3 Basic principles for creating references]

So I think you can choose which version of the resource you would like to cite.

> Is the medium designator based on the version of the work you actually consulted (probably the online version) or based on a version of the work that (probably) exists and that you could in theory get hold of? Does "online" mean _available (only) online_ or does it mean _I accessed it online_? How similar would a physical work and its online version have to be to qualify as "the same" so that you can drop the "online" designator even though you only read the online version?

Good questions! I can put here the excerpts from the standard:

> If necessary, information about the nature of the information resource and/or the form in which it is made available should be given in brackets.

[1, sec 7 Medium designation]

And specifically for the electronic resources:
> The type of medium for the electronic information resource should be given in the medium designation (see Clause 7).

[1, sec 15.2.2 Type of medium]

> How similar would a physical work and its online version have to be to qualify as "the same" so that you can drop the "online" designator even though you only read the online version?

I think that technically it is possible to upload a newer version of the thesis in the digital archive (I would say very exceptional special cases), so it is not necessary 1:1 of the printed and the electronic form, so we should distinguish which form we reference.

[1] ISO 690: Information and documentation -- Guidelines for bibliographic references and citations to information resources. Third edition. Geneva: The International Organization for Standardization, 2010.

**Comment by moewew** [comment]
This is just me ranting, so feel free to ignore this.

I was afraid the driving factor behind this change was to get rid of "[online]" because online sources (or rather, sources marked with "[online]") are somehow seen as less trustworthy, less stable or generally inferior. As such the attempt to argue for removal of the "[online]" label for theses seemed like a way to make them appear more citable. I fundamentally disagree with that view.

What I understood from Google Translate https://www.herout.net/blog/2010/08/evergreen-citovani-webu-vs-papiru/ goes in that direction.

First and foremost I believe that one should always cite the version of the source one actually read. 

Let's assume for the moment that in the example mentioned in https://www.herout.net/blog/2010/08/evergreen-citovani-webu-vs-papiru/ the online version of the paper (ftp://ftp.vision.ee.ethz.ch/publications/articles/eth_biwi_00517.pdf) is a preprint uploaded by the authors of the paper to their personal webpage, which differs only in the layout from the article actually published in the journal (the preprint uses the article class and page numbers 1-24; the published article is of course formatted by the publisher, so page breaks etc. are different). (My point still stands, even on stronger ground, if the preprint version differs from the published version.)

If I only obtained ftp://ftp.vision.ee.ethz.ch/publications/articles/eth_biwi_00517.pdf then it is proper to cite

> BAY, Herbert; ESS, Andreas; TUYTELAARS, Tinne; GOOL, Luc Van: Speeded-Up Robust Features (SURF) [online]. 2006, updated 2008 [cit. 2010-07-13].
Accessible from WWW: ftp://ftp.vision.ee.ethz.ch/publications/articles/eth_biwi_00517.pdf

Indeed it would be scientifically dishonest to cite

> Herbert Bay, Andreas Ess, Tinne Tuytelaars, Luc Van Gool, „SURF: Speeded Up Robust Features“, Computer Vision and Image Understanding (CVIU), Vol. 110, No. 3, pp. 346–359, 2008

if I did not lay my hands (or at least) eyes on the published article (either by looking at the print version in my local library, by going to the publisher's website).

Of course that question is largely independent on whether or not I should read ftp://ftp.vision.ee.ethz.ch/publications/articles/eth_biwi_00517.pdf or where I should try and obtain a copy of the published article.

---

Simplifications like "don't cite the online version, cite the published/printed version" cause people to see everything that has "[online]" in it as immediately less citable. So much so that they try to argue away the "[online]" to make a source look better.

That's why I think the "[online]" medium designator isn't that helpful in general: It will just put people off perfectly citable sources. Usually people can tell if something is an online source without the designator anyway. To determine whether something is citable or not it is not that important whether something is an online source *per se*, but what kind of online source it is. Would a peer-reviewed scientific journal of generally good standing be a bad "[online]" source if it ceased to published printed journal volumes?


---

I must say I don't find the standard particularly clear here.

It is for example not clear to me when something is an "electronic resource" (in particular if there is a non-electronic version).

It is also not clear to me how I can tell if it is "necessary" to give the nature of the information resource in

> If necessary, information about the nature of the information resource and/or the form in which it is made available should be given in brackets.

**Comment by DavidLuptak** [comment]
Maybe I simplified to myself the examples from the https://www.herout.net/blog/2010/08/evergreen-citovani-webu-vs-papiru/, but I understand it that they wanted to stress the difference that one will 1) cite the PDF, not the 2) content of that PDF, even though we are talking about the _same_ PDF file:

1) this includes where the PDF can be obtained
2) this includes the _context_ (name of the journal, volume of the journal and its issue number)

In other points, I generally agree with your point of view.

And the standard is generally vague, so it is not a surprise that everyone can interpret it their way.
