### ISSUE TITLE
'Corporate authors' need to be protected with curly braces

### ISSUE THREAD

**Issue by megi-mejdrechova** [michal-h21/biblatex-iso690#92]
Hey,
I found an older issue https://github.com/michal-h21/biblatex-iso690/issues/88, where you suggest to protect 'Corporate authors' with curly braces in order to prevent formating as FAMILYNAME, Name. 

I tried the trick with {{Corporate authors}}, but nothing changed. It is still printed as AUTHORS, Corporate.

I import your package this way:
\usepackage[backend=biber,style=iso-numeric]{biblatex}

Do you have any idea what may be wrong and why the double curly braces do not help?

Thank you very much for your help and also for the package :)

**Comment by moewew** [comment]
Did you rerun Biber and LaTeX after you fixed your `.bib` file? `author = {{Corporate authors}},` should be correct.
```latex
\documentclass[english]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

 \usepackage[backend=biber,style=iso-numeric]{biblatex}

\begin{filecontents}{\jobname.bib}
@book{corporate,
  author    = {{Corporate authors}},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
Lorem \autocite{sigfridsson,corporate}

\printbibliography
\end{document}
```

> CORPORATE AUTHORS. A Theory on Brontosauruses. London: Monthy & Co., 1972.

![image of output, the relevant section with "CORPORATE AUTHORS" has been quoted above](https://user-images.githubusercontent.com/6755835/115346935-15aee980-a1b1-11eb-98ec-59805b2b2dbf.png)

**Comment by DavidLuptak** [comment]
I suppose this is a compilation or TeX distribution setup issue. We provide also some examples in the [`biblatex-iso690-examples.bib`](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690-examples.bib), see e.g. [`@groll2008method`](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690-examples.bib#L231) or [`@dialog1985enhancements`](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690-examples.bib#L428) and compare with the reference bibliography in [our documentation](https://github.com/michal-h21/biblatex-iso690/blob/master/biblatex-iso690.pdf#section.3).

- [x] Emphasized corporate authors in the documentation 776526eb02694c942787f41e40acb8228ddb1075, since it seems to be a repetitive issue for the users.

I am closing this issue now, @megi-mejdrechova if you would have any further issues, we are happy to help :sos:
